// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgza9Cgjq6hM3krWPoYruYm_kw9iQdf7I',
    appId: '1:563168944003:web:9b4dad636cc661815d20b6',
    messagingSenderId: '563168944003',
    projectId: 'cs310-spring-2025-group-29',
    authDomain: 'cs310-spring-2025-group-29.firebaseapp.com',
    storageBucket: 'cs310-spring-2025-group-29.firebasestorage.app',
    measurementId: 'G-QCD29QM7MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5p-jqKKq9MTOe_ZxkoXnFMd79F-LF5rk',
    appId: '1:563168944003:android:a4457c98e2d7dfe75d20b6',
    messagingSenderId: '563168944003',
    projectId: 'cs310-spring-2025-group-29',
    storageBucket: 'cs310-spring-2025-group-29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhT6DB1LTMcWxd2gZniDkfUuAggwQPZs',
    appId: '1:563168944003:ios:976edc057c6f068d5d20b6',
    messagingSenderId: '563168944003',
    projectId: 'cs310-spring-2025-group-29',
    storageBucket: 'cs310-spring-2025-group-29.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgza9Cgjq6hM3krWPoYruYm_kw9iQdf7I',
    appId: '1:563168944003:web:01d09b6ea341b2085d20b6',
    messagingSenderId: '563168944003',
    projectId: 'cs310-spring-2025-group-29',
    authDomain: 'cs310-spring-2025-group-29.firebaseapp.com',
    storageBucket: 'cs310-spring-2025-group-29.firebasestorage.app',
    measurementId: 'G-YTE9X64C65',
  );
}
